import Web3 from "web3";

export interface appStore {
  chainId: number | undefined;
  walletAddress: string;
  walletIsActive: boolean;
  wallet: any;
  chainName: string;
  currencySymbol: string;
  rpcUrl: string;
  blockExplorerUrl: string;
  confirmLimit: number;
  getPriceUrl: string;
  get24hrPriceUrl: string;
  zeroAddress: string;
  ETH: string;
  WETH: string;
  WBTC: string;
  USDC: string;
  price_btc_aave: number;
  price_eth_aave: number;
  price_usdc_aave: number;
  price_btc_bsc: number;
  price_eth_bsc: number;
  price_usdc_bsc: number;
  price_btc_change: number;
  price_eth_change: number;
  price_usdc_change: number;
  dsa_wbtc_balance: number;
  dsa_weth_balance: number;
  dsa_usdc_balance: number;
  wallet_wbtc_balance: number;
  wallet_eth_balance: number;
  wallet_usdc_balance: number;
  dsa_address: string;
  web3: Web3 | null;
  dlgWalletConnect: boolean;
  dlgCreateDsa: boolean;
  dlgGetStarted: boolean;
  dlgGetStartedTab: string;
  dlgDeposit: boolean;
  dlgWithdrawDsa: boolean;
  dlgWithdrawAave: boolean;
  dlgSwap: boolean;
  dlgSupply: boolean;
  dlgBorrowRepay: boolean;
  dlgBorrow: boolean;
  dlgRepay: boolean;
  dlgLoop: boolean;
  dlgDeloop: boolean;
  dlgShield: boolean;
  dlgSwapEnable: boolean;
  aaveV3Usdc_supply: number;
  aaveV3Weth_supply: number;
  aaveV3Wbtc_supply: number;
  aaveV3Usdc_borrow: number;
  aaveV3Weth_borrow: number;
  aaveV3Wbtc_borrow: number;
  aaveV3_total_collateral_base: number; // in usd
  aaveV3_total_debt_base: number; //in usd
  aaveV3_available_borrows_base: number;
  aaveV3_current_liquidation_threshold: number;
  aaveV3_ltv: number;
  aaveV3_health_factor: number;
  health_factor_risky: number;
  health_factor_safe: number;
  aaveV3UsdcLiquidityRate: number;
  aaveV3UsdcVariableBorrowRate: number;
  aaveV3WethLiquidityRate: number;
  aaveV3WethVariableBorrowRate: number;
  aaveV3WbtcLiquidityRate: number;
  aaveV3WbtcVariableBorrowRate: number;
  closeOptLimit: number;
  shield_trigger: number;
  shield_target: number;
  isMobile: boolean;
  isSmall: boolean;
  doc_url: string;
  doc_url_deposit: string;
  doc_url_withdraw: string;
  doc_url_borrow: string;
  doc_url_repay: string;
  doc_url_supply: string;
  doc_url_swap: string;
  doc_url_loop: string;
  doc_url_deloop: string;
  doc_url_shield: string;
}
